apiVersion: v1
kind: Service
  metadata:
    name: spring-boot-app-service
  spec:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 6500
      protocol: TCP
    selector:
      app: spring-boot-app
